databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
 - type: redis
    name: sidekiq-redis
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections
  - type: job
    name: sidekiq-job
    runtime: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
     
      - key: REDIS_URL # this must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: recruitment_portal_redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default

- type: web
    name: recruitment_portal
    runtime: ruby
    region: ohio
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: recruitment_portal_redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  
