databases:
  - name: recruitment_portal
    databaseName: recruitment_portal
    plan: free

services:
  - type: web
    name: recruitment_portal
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitment_portal
      - key: RAILS_MASTER_KEY
        value: 068cfabae22bf2dc93530b23ac93f76f
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
